### PR TITLE
Add map option to allow transforming and filtering files

### PR DESCRIPTION
**Pull request by DavidBeale**
Add map option to allow transforming and filtering files

### CODE REVIEW

**Comment by coderaiser** [comment]
Thank you, I should think about it. Can you tell me please, why you need it?

**Comment by DavidBeale** [comment]
Hi. I would like to filter out files, and change their paths In order to create a zip file from an npm package. Picking out the "dist" directory etc and using it to deploy to a product with requires zip file uploads.

**Comment by coderaiser** [comment]
It is a really good idea. But I think would be better to use 2 functions:
- [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) to check if a files satisfies condition by attributes in `header` field:

```js
const filter = ({name}) => {
    return name === 'name.txt';
}
```

- [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) to patch some fields of a `header` of the files:

```js
const map = ({name}) => {
   return {
      name: name + '123'
  }
}
```

`filter` should be called first, and then `map`:

```js
this._filter = filter || () => true;
this._map = map || () => {};

tar.on('entry', (sourceHeader, stream, next) => {      
    if (!this._filter(sourceHeader))
       return;
    
    const header = Object.assign(sourceHeader, this._map(sourceHeader));
});
```

What do you think about it?

**Comment by DavidBeale** [comment]
Hi,

I was copying the pattern from map-stream, but happy to go your way.

Would you like me to make the changes?

Thanks,

   David

**Comment by coderaiser** [comment]
> Would you like me to make the changes?

Yes, it would be great :).

**Comment by coderaiser** [comment]
Thank you :), merged as 6da6acc. Landed in [v1.3.0](https://github.com/coderaiser/node-tar-to-zip/releases/tag/v1.3.0).

**Comment by DavidBeale** [comment]
Great

**Pull request closed without merging**
